name: Build and Push

on:
  release:
    types: [published]
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            insrapperswil/okteto-dev-golang:latest
            insrapperswil/okteto-dev-golang:${{ steps.vars.outputs.tag }}
